# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build Validation

on:
  push:
    branches: [ "cross.1.2025.326.1" ]
  pull_request:
    branches: [ "cross.1.2025.326.1" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Display dotnet version
      run: dotnet --version
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore dependencies
      run: msbuild './SurfaceDevCenterManager/SurfaceDevCenterManager.csproj' -t:restore -property:Configuration=Release
    
    - name: Build app for release    
      run: msbuild './SurfaceDevCenterManager/SurfaceDevCenterManager.csproj' -t:build -property:Configuration=Release
